name: AniRe CI

on:
    push:
        branches: [ main, dev ]
    pull_request:
        branches: [ main, dev ]

jobs:
  linting:
      runs-on: ubuntu-latest

      steps:
      - name: "Checkout Repo"
        uses: actions/checkout@v4

      - name: "Install Node"
        uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: npm

      - name: "NPM CI"
        run: npm ci

      - name: "Lint - Check for errors & unused vars on package core"
        run: npm run lint